[주시현] 멋쟁이 사자처럼 3번쨰 과제 제출
Likelion-Inha-10/fe-week3 pull request #2
Opened 2022-05-14 06:50 UTC by sean2337

![week3 앱 사진1(주시현)](https://user-images.githubusercontent.com/100525337/168414430-99d32639-316a-4eee-aaea-dfab4463f6b7.JPG)
![week3 앱 사진2(주시현)](https://user-images.githubusercontent.com/100525337/168414431-3fe0977c-b89f-475b-a185-724fc7983231.JPG)
![week3 앱 사진3(주시현)](https://user-images.githubusercontent.com/100525337/168414432-0b0a1680-f69f-4f6f-b273-479eeec4fbf0.JPG)

2022-05-14 15:23 UTC, devHudi commented on src/App.js
> +      />
React 에서 컴포넌트라는 개념은 무엇이고, 왜 사용하는 것 일까요? 저는 컴포넌트란 웹에서 보여지는 UI를 작은 단위로 분리하여 재사용하기 용이한 형태로 나누어 놓은 단위라고 생각해요.

하지만 이런 구조에서는 의도한대로 `Card` 컴포넌트를 재사용하기 힘들 것이라고 생각되어요. `Card` 가 너무 많은 요소를 포함하고 있는 것은 아닐까요? 다른 개발자가 이 `Card` 컴포넌트를 사용하면 어떤 UI 요소가 나타날것이라고 생각할까요? 

시현님이 생각하는 `Card` 란 어떤 UI 요소인지 한번 고민해보면 의미있는 과정이 될 것 같아요 😎

2022-05-14 15:24 UTC, devHudi commented on src/App.js
> +      />
재사용과 재사용성이 무엇일까요? 한번 찾아보는 것도 도움이 될 것 같네요.

2022-05-14 15:24 UTC, devHudi commented on src/component/Card/index.js
> +          <Title2>
다른 개발자가 보았을 때 `Title` 과 `Title2` 의 이름만을 보고 어떤 역할을 하는 컴포넌트인지 이해할 수 있을까요? 어떤 네이밍이 좋은 네이밍일까요?

2022-05-14 15:25 UTC, devHudi commented on src/component/GlobalStyle.js
> +export default GlobalStyle;
`GlobalStyle` 👍👍

2022-05-14 15:26 UTC, devHudi requested changes
포켓몬을 주제로 클론코딩 해주셨군요 ㅎㅎ
지난주 과제 때 보다 훨씬 성장하신 것 같아요 👍
몇가지 수정하면 좋을 만한 점을 코멘트 달아드렸어요. 반영해주셔도 좋고, 참고만 해주셔도 좋습니다 😁

2022-05-14 17:07 UTC, devHudi requested changes

2022-05-14 17:07 UTC, devHudi commented on src/component/Card/index.js
> +  margin-right: 5px; //원래 있는거 아님;;
기본값을 위해 삼항연산자가 반복적으로 사용되고 있는데요, 아래와 같은 방법으로 코드를 좀 더 축약해볼 수 있을 것 같아요.

### AS-IS

```css
color: ${(props) => props.color ? props.color : "#212529"};
```

### TO-BE

```css
color: ${(props) => props.color || "#212529"};
```

이를 단축 평가 (Short circuit evaluation) 이라고 합니다. (참고: http://milooy.github.io/TIL/JavaScript/short-circuit.html#%E1%84%8B%E1%85%A8%E1%84%8C%E1%85%A6)

2022-05-15 03:06 UTC, pcpark98 approved these changes
지난주에 비해 확실히 발전한 모습이 보입니다!

수고하셨어요. 다음 주도 화이팅~~~

2022-05-16 04:30 UTC, merged