[최재오] 멋쟁이 사자처럼 3번째 과제 제출
Likelion-Inha-10/fe-week3 pull request #6
Opened 2022-05-14 15:57 UTC by jaeochoii

<img width="1728" alt="스크린샷 2022-05-15 오전 12 52 33" src="https://user-images.githubusercontent.com/103018984/168439437-e5672bb4-b154-4ece-83a6-14218e252873.png">
<img width="1728" alt="스크린샷 2022-05-15 오전 12 53 02" src="https://user-images.githubusercontent.com/103018984/168439450-32df1355-7e2b-4fd1-9d2a-4ae54aa87766.png">

2022-05-14 17:06 UTC, devHudi requested changes

2022-05-14 17:06 UTC, devHudi commented on src/component/CardWrapper/index.js
> +  console.log(props);
디버깅을 위한 콘솔 로그는 제거할까요?

2022-05-14 17:06 UTC, devHudi commented on src/component/CardWrapper2/index.js
> +        <ImageCard2 picture="img/튜브.png"/>
전체적으로 컴포넌트 명이 `CardWrapper`, `CardWrapper2`, `CardWrapper3` 와 같이 넘버링을 사용하여 네이밍 되어 있어요. 재오님과 협업하는 다른 개발자가 컴포넌트 명을 보았을 때, `CardWrapper2` 가 다른`CardWrapper` 와 어떤 차이점을 가지는지 한눈에 알 수 있을까요? 좋은 네이밍이란 무엇일까요? 어떻게 하면 협업에서 발생하는 커뮤니케이션의 비용을 줄일 수 있을까요? 🤔

2022-05-14 17:06 UTC, devHudi commented on src/component/Content/index.js
> +  height: 90px;
`font-family` 속성에 해당하는 값이 아주 길군요. 그리고 다른 여러 컴포넌트에서 중복적으로 사용되고 있어요. 어떻게 하면 이 중복을 줄일 수 있을까요? 부모 컴포넌트에서 한번에 지정하는 방법도 적용해볼 수 있을 것 같고, 폰트가 아예 프로젝트 globally 하게 사용된다면 styled components 의 `GlobalStyle` 를 고려해볼수도 있을 것 같네요 🤔

2022-05-14 17:06 UTC, devHudi commented on src/component/CardWrapper/index.js
> +  font-size: 16px;
기본값을 위해 삼항연산자가 반복적으로 사용되고 있는데요, 아래와 같은 방법으로 코드를 좀 더 축약해볼 수 있을 것 같아요.

### AS-IS

```css
color: ${(props) => props.color ? props.color : "#212529"};
```

### TO-BE

```css
color: ${(props) => props.color || "#212529"};
```

이를 단축 평가 (Short circuit evaluation) 이라고 합니다. (참고: http://milooy.github.io/TIL/JavaScript/short-circuit.html#%E1%84%8B%E1%85%A8%E1%84%8C%E1%85%A6)

2022-05-14 17:10 UTC, devHudi commented
이번엔 소스코드가 안날라가서 다행이군요 🤣 깃이 참 어렵죠...
몇가지 수정하면 좋을 만한 점을 코멘트 달아드렸어요. 반영해주셔도 좋고, 참고만 해주셔도 좋습니다 😁

2022-05-15 03:51 UTC, jaeochoii commented on src/component/CardWrapper2/index.js
> +        <ImageCard2 picture="img/튜브.png"/>
죄송합니다 😭

2022-05-15 04:28 UTC, jaeochoii commented on src/component/Content/index.js
> +  height: 90px;
success!

2023-12-11 11:57 UTC, closed without merging